name: 9anime Transloader

on:
  workflow_dispatch:
    inputs:
      PlaylistURL:
        description: "Playlist URL"
        required: true
        default: ""
        type: string
      AniName:
        description: "Anime Name"
        required: true
        default: ""
        type: string
      EpCode:
        description: "EpCode, 1x03|2x01"
        required: true
        default: ""
        type: string
      SpeedProf:
        description: "SpeedProf"
        required: true
        default: "-"
        type: choice
        options:
        - "-"
        - "0x576"
        - "3x576"
        - "2x576"
        - "0x450"
        - "3x450"
        - "2x450"
        - "2x360"
      QCTest:
        description: "Enable QC Check?"
        required: false
        type: boolean
        default: false
      DubbedAud:
        description: "English Dubbed?"
        required: false
        type: boolean
        default: false
      AggrDenoise:
        description: "Enable Aggressive Frame Denoising?"
        required: false
        type: boolean
        default: false

env:
  SOURCERY: ${{ secrets.SOURCERY }}
  LocationOnIndex: "td:/9animeStreamZ"
  ChunkLocationOnIndex: "td:/9animeChunkZ"
  AniName: ${{ github.event.inputs.AniName }}
  EpCode: ${{ github.event.inputs.EpCode }}
  DubbedAud: ${{ github.event.inputs.DubbedAud }}
  SpeedProf: ${{ github.event.inputs.SpeedProf }}
  AggrDenoise: ${{ github.event.inputs.AggrDenoise }}
  QCTest: ${{ github.event.inputs.QCTest }}
  RCLONE_CONFIG_URL: ${{ secrets.RCLONE_CONFIG_URL }}

jobs:
  primary:
    name: Transloader
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: GitHub Auth
        uses: rokibhasansagar/custom_workflows/git_config@main
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: Checkout EncToolZ
        env:
          ReqdEncToolZ: "ftools mtools rtools ytools"
        run: |
          eval 'set -eo pipefail' 2>/dev/null && eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY
          source ./SOURCERY &>/dev/null && rm -f ./SOURCERY && eval 'set -o history' 2>/dev/null
          DEOBFUS ./21-EncTool-b473ab7b69f5
      - name: "AniLoad Job - ${{env.AniName}} - ${{env.EpCode}}"
        env:
          PlaylistURL: ${{ github.event.inputs.PlaylistURL }}
        run: |
          eval 'set -eo pipefail' 2>/dev/null && eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY
          source ./SOURCERY &>/dev/null && rm -f ./SOURCERY && eval 'set -o history' 2>/dev/null
          DEOBFUS ./33-EncTrns-fab7572c4e16
          DEOBFUS ./37-EncGnrt-17e086dd6e4a
      - name: "API Sequencer - ${{env.AniName}} - ${{env.EpCode}}"
        if: env.SpeedProf != '-'
        env:
          GH_TOKEN2: ${{ secrets.GH_TOKEN2 }}
        run: |
          eval 'set -eo pipefail' 2>/dev/null && eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY
          source ./SOURCERY &>/dev/null && rm -f ./SOURCERY && eval 'set -o history' 2>/dev/null
          DEOBFUS ./97-EncSqnc-00e78d1bd279
